server:
  port: 5015

spring:
  application:
    name: ngepost
  profiles:
    active: prod

jwt:
  secret: "thisIsASuperLongSecretKeyWithAtLeast32Chars!"
  expiration: 86400000
  customer:
    expiration: 604800000